title:            Overlook Endurance Runs
tagline:          A short tagline 
description:      Describe your website.
# Your site's domain goes here. Leave localhost server or blank when working locally.
# url:              http://localhost:4000 
url: http://trason-trail-races.github.io/overlook-endurance-runs 

# Owner/author information
owner:
  name:           Overlook Endurance Runs
  avatar:         logo.png
  bio:            ""
  email:          your@email.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter: overlook-endurance-runs
  facebook: overlook-endurance-runs
  github:         
  linkedin:       
  instagram: overlook-endurance-runs
  lastfm:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Course Info
    url: /courseinfo
  - title: Race Info
    url: /raceinfo   
  - title: Register
    url: /register
  - title: Contact
    url: /contact    

  # - title: About
  #   url: /about/
  # - title: Articles
  #   url: /articles/
  # - title: Theme Setup
  #   url: /theme-setup/
  # - title: Made Mistakes
  #   url: http://mademistakes.com
  #   external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]